services:
  slack-bot:
    build: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - JELLYSEERR_API_URL=${JELLYSEERR_API_URL}
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY}
    ports:
      - "3000:3000"
