version: "3"

services:
  pihole:
    extends:
      file: ./services/pihole.yml
      service: pihole
  homeassistant:
    extends:
      file: ./services/homeassistant.yml
      service: homeassistant
  jellyfin-slackbot:
    extends:
      file: ./services/jellyfin-slackbot.yml
      service: slack-bot
