name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # We really want to do this for each machine,
    # but we aren't even realistically managing the pi this way yet, anyway
    - name: Validate Docker Compose file
      run: docker-compose -f machines/pi/docker-compose.yml config
